
// This is a sample DID generated by the DIDGenerator
// ignore_for_file: avoid_print
import 'dart:convert';

import 'package:did_key_dart/did_key_dart.dart';
import 'package:jose/jose.dart';

void main() {
  const awesome = DIDKeyDriver();
  final jwk = JsonWebKey.generate('ES256');
  print(jwk.toJson());
  final did = awesome.generateDIDFromJWK(
    keyAlgorithm: P256(),
    jwk: jsonEncode(jwk.toJson()),
  );
  print('Sample DID: $did');
}
