name: did_key_dart
description: A Dart package for generating and resolving Decentralized Identifiers (DIDs) using various cryptographic algorithms, including P-256 and Ed25519. This package provides functionality to create DIDs, resolve them to obtain public keys.
version: 0.1.0
repository: https://github.com/WtrN/did_key_dart

environment:
  sdk: ^3.5.3

dependencies:
  base_x: ^2.0.1
  crypto_keys: ^0.3.0
  jose: ^0.3.4
  pointycastle: ^3.9.1
  quiver: ^3.2.2

dev_dependencies:
  altive_lints: ^1.14.1
  lints: ^5.0.0
  test: ^1.25.8
