name: dart_ssi
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  crypto_keys: ^0.3.0
  pointycastle: ^3.9.1
  jose: ^0.3.4
  base_x: ^2.0.1
  quiver: ^3.2.2

dev_dependencies:
  altive_lints: ^1.14.1
  lints: ^4.0.0
  test: ^1.24.0
